import React,{useEffect,useMemo,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {BrowserRouter} from 'react-router-dom'
import {LayoutDashboard,ShoppingCart,Receipt,Package,Truck,Users,Building2,WalletCards,Landmark,BarChart3,Settings,Menu,Search,Plus,RefreshCw,LogOut,ChevronLeft,ChevronRight,Trash2,Pencil,Download,AlertTriangle,ArrowUpRight,ArrowDownRight,IndianRupee,X,Save,UserRound,Fuel,HandCoins,FileText} from 'lucide-react'
import {auth,getDashboard,listResource,createResource,updateResource,deleteResource} from './api'
import './styles.css'

const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`
const today=()=>new Date().toISOString().slice(0,10)
const nav=[
 {key:'dashboard',label:'Dashboard',icon:LayoutDashboard},
 {key:'sales',label:'Sales',icon:ShoppingCart}, {key:'expenses',label:'Expenses',icon:Receipt},
 {key:'purchases',label:'Purchases',icon:Package}, {key:'products',label:'Stock',icon:Package},
 {key:'petrol',label:'Petrol',icon:Fuel}, {key:'allowance',label:'Allowance',icon:HandCoins},
 {key:'salary',label:'Salary',icon:WalletCards}, {key:'partners',label:'Partners',icon:Users},
 {key:'customers',label:'Customers',icon:UserRound}, {key:'suppliers',label:'Suppliers',icon:Building2},
 {key:'cash',label:'Cash',icon:WalletCards}, {key:'bank',label:'Bank',icon:Landmark},
 {key:'transactions',label:'Transactions',icon:FileText}, {key:'reports',label:'Reports',icon:BarChart3},
 {key:'settings',label:'Settings',icon:Settings}
]
const schemas={
 customers:{title:'Customers',singular:'Customer',fields:[['name','Customer name','text',true],['business_name','Business name','text'],['phone','Phone','text'],['email','Email','email'],['address','Address','textarea'],['notes','Notes','textarea']]},
 suppliers:{title:'Suppliers',singular:'Supplier',fields:[['name','Supplier name','text',true],['business_name','Business name','text'],['phone','Phone','text'],['email','Email','email'],['address','Address','textarea'],['notes','Notes','textarea']]},
 categories:{title:'Categories',singular:'Category',fields:[['name','Category name','text',true]]},
 products:{title:'Stock',singular:'Product',fields:[['name','Product name','text',true],['code','Product code','text'],['purchase_price','Purchase price','number'],['selling_price','Selling price','number'],['opening_stock','Opening stock','number'],['stock_added','Stock added','number'],['stock_sold','Stock sold','number'],['adjustment','Adjustment','number'],['minimum_stock','Minimum stock','number'],['unit','Unit','text'],['notes','Notes','textarea']]},
 sales:{title:'Sales',singular:'Sale',fields:[['date','Date','date',true],['customer','Customer ID','number'],['product','Product ID','number'],['quantity','Quantity','number',true],['selling_price','Selling price','number',true],['amount_received','Amount received','number'],['payment_mode','Payment mode','select'],['reference','Invoice / reference','text'],['notes','Notes','textarea']]},
 purchases:{title:'Purchases',singular:'Purchase',fields:[['date','Date','date',true],['supplier','Supplier ID','number'],['product','Product ID','number'],['quantity','Quantity','number',true],['purchase_price','Purchase price','number',true],['amount_paid','Amount paid','number'],['payment_mode','Payment mode','select'],['invoice_number','Invoice number','text'],['notes','Notes','textarea']]},
 expenses:{title:'Expenses',singular:'Expense',fields:[['date','Date','date',true],['category','Expense category','text',true],['sub_category','Sub-category','text'],['description','Description','text',true],['amount','Amount','number',true],['payment_mode','Payment mode','select'],['paid_by','Paid by','text'],['classification','Business / Personal','select2'],['notes','Notes','textarea']]},
 petrol:{title:'Petrol & Travel',singular:'Petrol entry',fields:[['date','Date','date',true],['vehicle','Vehicle','text',true],['person','Driver / Person','text'],['purpose','Purpose','text'],['start_location','Starting location','text'],['destination','Destination','text'],['odometer','Odometer','number'],['km','Kilometer travelled','number'],['petrol_quantity','Petrol quantity','number'],['petrol_amount','Petrol amount','number'],['toll','Toll','number'],['parking','Parking','number'],['other','Other travel expense','number'],['paid_by','Paid by','text'],['notes','Notes','textarea']]},
 allowance:{title:'Employee Allowance',singular:'Allowance',fields:[['date','Date','date',true],['employee','Employee','text',true],['allowance_type','Allowance type','select3',true],['amount','Amount','number',true],['purpose','Purpose','text'],['payment_mode','Payment mode','select'],['paid_by','Paid by','text'],['notes','Notes','textarea']]},
 salary:{title:'Salary',singular:'Salary record',fields:[['employee','Employee','text',true],['salary_month','Salary month','month',true],['basic','Basic salary','number',true],['allowance','Allowance','number'],['additions','Other additions','number'],['deductions','Deductions','number'],['payment_date','Payment date','date'],['payment_mode','Payment mode','select'],['status','Payment status','select4'],['notes','Notes','textarea']]},
 partners:{title:'Partners',singular:'Partner',fields:[['name','Partner name','text',true],['phone','Phone','text'],['email','Email','email'],['joining_date','Joining date','date'],['share_percent','Profit share %','number'],['initial_capital','Initial capital','number'],['additional_investment','Additional investment','number'],['withdrawals','Withdrawals','number'],['notes','Notes','textarea']]},
 cash:{title:'Cash Transactions',singular:'Cash transaction',fields:[['date','Date','date',true],['transaction_type','Transaction type','select5',true],['description','Description','text',true],['amount','Amount','number',true],['reference','Reference','text']]},
 bank:{title:'Bank Transactions',singular:'Bank transaction',fields:[['date','Date','date',true],['transaction_type','Transaction type','select5',true],['description','Description','text',true],['amount','Amount','number',true],['reference','Reference','text'],['bank_name','Bank name','text']]},
 transactions:{title:'General Transactions',singular:'Transaction',fields:[['date','Date','date',true],['transaction_type','Transaction type','select5',true],['category','Category','text',true],['description','Description','text',true],['amount','Amount','number',true],['payment_mode','Payment mode','select'],['person_company','Person / company','text'],['reference','Reference','text'],['notes','Notes','textarea']]}
}
const opts={select:['Cash','UPI','Bank Transfer','Card','Other'],select2:['Business','Personal'],select3:['Food','Travel','Petrol','Daily Allowance','Accommodation','Other'],select4:['Pending','Paid','Partially Paid'],select5:['Income','Expense','Transfer','Adjustment']}

function App(){
 const [token,setToken]=useState(localStorage.getItem('kbm_token')); const [user,setUser]=useState(JSON.parse(localStorage.getItem('kbm_user')||'null')); const [page,setPage]=useState('dashboard'); const [mobileOpen,setMobileOpen]=useState(false)
 useEffect(()=>{const f=()=>{setToken(null);setUser(null)};window.addEventListener('auth-expired',f);return()=>window.removeEventListener('auth-expired',f)},[])
 if(!token) return <Login onLogin={(t,u)=>{localStorage.setItem('kbm_token',t);localStorage.setItem('kbm_user',JSON.stringify(u));setToken(t);setUser(u)}}/>
 const logout=()=>{localStorage.removeItem('kbm_token');localStorage.removeItem('kbm_user');setToken(null);setUser(null)}
 return <div className="app-shell"><aside className={`sidebar ${mobileOpen?'open':''}`}><div className="brand"><div className="brand-mark">K</div><div><b>Kavish</b><span>Business Management</span></div><button className="icon-btn mobile-only" onClick={()=>setMobileOpen(false)}><X size={20}/></button></div><nav>{nav.map(n=>{const I=n.icon;return <button key={n.key} className={page===n.key?'nav-item active':'nav-item'} onClick={()=>{setPage(n.key);setMobileOpen(false)}}><I size={18}/><span>{n.label}</span></button>})}</nav><div className="sidebar-bottom"><div className="user-mini"><div className="avatar">{(user?.username||'O')[0].toUpperCase()}</div><div><b>{user?.username||'Owner'}</b><span>Internal access</span></div></div><button className="nav-item" onClick={logout}><LogOut size={18}/><span>Logout</span></button></div></aside><main className="main"><header className="topbar"><button className="icon-btn mobile-only" onClick={()=>setMobileOpen(true)}><Menu/></button><div><h1>{pageTitle(page)}</h1><p>{pageSubtitle(page)}</p></div><div className="top-actions"><span className="status-dot">● Online</span><button className="icon-btn" onClick={()=>window.location.reload()} title="Refresh"><RefreshCw size={18}/></button></div></header><section className="content">{page==='dashboard'?<Dashboard/>:page==='reports'?<Reports/>:page==='settings'?<SettingsPage user={user}/>:<ResourcePage resource={page}/>}</section></main></div>
}
function pageTitle(p){return nav.find(x=>x.key===p)?.label||'Dashboard'}
function pageSubtitle(p){return p==='dashboard'?'A simple view of your business today.':p==='reports'?'Review business performance by period.':p==='settings'?'Business preferences and account tools.':'Manage your records and keep every transaction traceable.'}
function Login({onLogin}){const [username,setUsername]=useState('owner'),[password,setPassword]=useState('ChangeMe123!'),[busy,setBusy]=useState(false),[err,setErr]=useState('');const submit=async e=>{e.preventDefault();setBusy(true);setErr('');try{const d=await auth.login(username,password);onLogin(d.token,{username})}catch(e){setErr(e.response?.data?.non_field_errors?.[0]||'Login failed. Check the username and password.')}finally{setBusy(false)}};return <div className="login-page"><div className="login-card"><div className="brand login-brand"><div className="brand-mark">K</div><div><b>Kavish</b><span>Business Management</span></div></div><h1>Welcome back</h1><p className="muted">Sign in to manage your business records.</p><form onSubmit={submit}><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>{err&&<div className="alert error">{err}</div>}<button className="primary full" disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form><div className="login-note">Internal users only · Customers do not get login access.</div></div></div>}
function Dashboard(){const [d,setD]=useState(null),[err,setErr]=useState('');useEffect(()=>{getDashboard().then(setD).catch(e=>setErr('Could not load dashboard. Make sure Django is running on port 8001.'))},[]);if(err)return <div className="alert error">{err}</div>;if(!d)return <Loading/>;const cards=[['Today Sales',d.today_sales,'up'],['Today Expenses',d.today_expenses,'down'],['Today Profit',d.today_profit,d.today_profit>=0?'up':'down'],['Cash Balance',d.cash_balance],['Bank Balance',d.bank_balance],['Stock Value',d.stock_value],['Receivables',d.receivables],['Payables',d.payables]];return <><div className="welcome-row"><div><h2>Business overview</h2><p className="muted">Today · {new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</p></div><div className="badge">Live database</div></div><div className="stats-grid">{cards.map(([t,v,dir])=><div className="stat-card" key={t}><div className="stat-top"><span>{t}</span>{dir==='up'?<ArrowUpRight size={17}/>:dir==='down'?<ArrowDownRight size={17}/>:<IndianRupee size={17}/>}</div><strong>{money(v)}</strong><small>{t==='Today Profit'?'Calculated from saved sales and expenses':'Current recorded value'}</small></div>)}</div><div className="dashboard-grid"><div className="panel"><div className="panel-head"><div><h3>Business health</h3><p>Quick operational indicators</p></div></div><div className="health-list"><div><span>Low stock items</span><b>{d.low_stock}</b></div><div><span>Sales today</span><b>{d.sales_count}</b></div><div><span>Expenses today</span><b>{d.expense_count}</b></div><div><span>Pending receivables</span><b>{money(d.receivables)}</b></div><div><span>Pending payables</span><b>{money(d.payables)}</b></div></div></div><div className="panel"><div className="panel-head"><div><h3>Financial snapshot</h3><p>Simple calculation, no manual profit entry</p></div><BarChart3 size={22}/></div><div className="profit-box"><span>Today's operating profit</span><strong>{money(d.today_profit)}</strong><small>Sales − business expenses</small></div></div></div></>}
function Loading(){return <div className="loading"><RefreshCw className="spin"/> Loading data…</div>}
function ResourcePage({resource}){const schema=schemas[resource];if(!schema)return <div className="empty-state"><h3>Module not available yet</h3><p>This screen is reserved for a future module.</p></div>;return <Crud resource={resource} schema={schema}/>}
function Crud({resource,schema}){const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[err,setErr]=useState(''),[query,setQuery]=useState(''),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[page,setPage]=useState(1);const size=8;const load=()=>{setLoading(true);setErr('');listResource(resource).then(setRows).catch(()=>setErr('Could not load records.')).finally(()=>setLoading(false))};useEffect(load,[resource]);const filtered=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())),[rows,query]);const pages=Math.max(1,Math.ceil(filtered.length/size));const visible=filtered.slice((page-1)*size,page*size);useEffect(()=>{if(page>pages)setPage(pages)},[pages]);const remove=async id=>{if(!confirm('Delete this record? It will be soft-deleted by the backend.'))return;try{await deleteResource(resource,id);load()}catch{setErr('Delete failed.')}};return <><div className="toolbar"><div className="search"><Search size={18}/><input placeholder={`Search ${schema.title.toLowerCase()}…`} value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></div><div className="toolbar-actions"><button className="secondary" onClick={load}><RefreshCw size={16}/> Refresh</button><button className="primary" onClick={()=>{setEditing(null);setOpen(true)}}><Plus size={17}/> Add {schema.singular}</button></div></div>{err&&<div className="alert error">{err}</div>}{loading?<Loading/>:<div className="panel table-panel">{visible.length===0?<div className="empty-state"><Package size={28}/><h3>No records yet</h3><p>Add your first {schema.singular.toLowerCase()} to begin.</p><button className="primary" onClick={()=>setOpen(true)}><Plus size={16}/> Add record</button></div>:<><div className="table-wrap"><table><thead><tr><th>Details</th><th>Date / Updated</th><th>Amount / Value</th><th></th></tr></thead><tbody>{visible.map(r=><Row key={r.id} row={r} resource={resource} onEdit={()=>{setEditing(r);setOpen(true)}} onDelete={()=>remove(r.id)}/>)}</tbody></table></div><div className="pagination"><span>{filtered.length} record{filtered.length===1?'':'s'}</span><div><button className="icon-btn" disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/></button><b>{page} / {pages}</b><button className="icon-btn" disabled={page===pages} onClick={()=>setPage(p=>p+1)}><ChevronRight size={17}/></button></div></div></>}</div>} {open&&<FormModal resource={resource} schema={schema} initial={editing} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);load()}}/>}</>}
function Row({row,resource,onEdit,onDelete}){const label=resource==='sales'?`Sale #${row.id}`:resource==='purchases'?`Purchase #${row.id}`:row.name||row.description||row.employee||row.vehicle||row.transaction_type||`Record #${row.id}`;const date=row.date||row.payment_date||row.joining_date||row.created_at?.slice(0,10)||'—';const val=row.total_amount??row.amount??row.net_salary??row.purchase_price??row.selling_price??row.stock_value;return <tr><td><div className="row-main">{label}</div><div className="row-sub">ID {row.id}</div></td><td>{date}</td><td>{val!==undefined?money(val):'—'}</td><td><div className="row-actions"><button className="icon-btn" onClick={onEdit} title="Edit"><Pencil size={16}/></button><button className="icon-btn danger" onClick={onDelete} title="Delete"><Trash2 size={16}/></button></div></td></tr>}
function FormModal({resource,schema,initial,onClose,onSaved}){const [form,setForm]=useState(()=>{const x={};schema.fields.forEach(([k,,t])=>x[k]=initial?.[k]??(t==='date'?today():''));return x});const [busy,setBusy]=useState(false),[err,setErr]=useState('');const set=(k,v)=>setForm(f=>({...f,[k]:v}));const submit=async(e,another=false)=>{e.preventDefault();setBusy(true);setErr('');const payload={...form};schema.fields.forEach(([k,,t])=>{if(t==='number')payload[k]=payload[k]===''?0:Number(payload[k]);if(['date','month'].includes(t)&&payload[k]==='')delete payload[k];if(['number'].includes(t)&&['customer','product','supplier'].includes(k))payload[k]=payload[k]||null});try{if(initial)await updateResource(resource,initial.id,payload);else await createResource(resource,payload);if(another&&!initial){const x={};schema.fields.forEach(([k,,t])=>x[k]=t==='date'?today():'');setForm(x)}else onSaved()}catch(e){const data=e.response?.data;setErr(typeof data==='object'?Object.entries(data).map(([k,v])=>`${k}: ${Array.isArray(v)?v.join(', '):v}`).join(' | '):'Save failed. Check the entered values.')}finally{setBusy(false)}};return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><h2>{initial?'Edit':'Add'} {schema.singular}</h2><p>Saved records live in the Django database.</p></div><button className="icon-btn" onClick={onClose}><X/></button></div><form onSubmit={e=>submit(e,false)}><div className="form-grid">{schema.fields.map(([k,label,t,required])=><Field key={k} name={k} label={label} type={t} value={form[k]} required={required} onChange={v=>set(k,v)}/>)}</div>{calcHint(resource,form)}{err&&<div className="alert error">{err}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button>{!initial&&<button type="button" className="secondary" disabled={busy} onClick={e=>submit(e,true)}><Save size={16}/> Save & Add Another</button>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save'}</button></div></form></div></div>}
function Field({name,label,type,value,required,onChange}){if(type==='textarea')return <label className="field full-field">{label}{required&&' *'}<textarea value={value} required={required} onChange={e=>onChange(e.target.value)} /></label>;if(type.startsWith('select'))return <label className="field">{label}{required&&' *'}<select value={value} required={required} onChange={e=>onChange(e.target.value)}><option value="">Select…</option>{opts[type].map(o=><option key={o}>{o}</option>)}</select></label>;return <label className="field">{label}{required&&' *'}<input name={name} type={type==='month'?'month':type} value={value} required={required} step={type==='number'?'0.01':undefined} onChange={e=>onChange(e.target.value)}/></label>}
function calcHint(resource,f){if(resource==='sales')return <div className="calc-hint">Total amount: <b>{money(Number(f.quantity||0)*Number(f.selling_price||0))}</b> · Pending: <b>{money(Number(f.quantity||0)*Number(f.selling_price||0)-Number(f.amount_received||0))}</b></div>;if(resource==='purchases')return <div className="calc-hint">Total purchase: <b>{money(Number(f.quantity||0)*Number(f.purchase_price||0))}</b> · Pending: <b>{money(Number(f.quantity||0)*Number(f.purchase_price||0)-Number(f.amount_paid||0))}</b></div>;if(resource==='petrol')return <div className="calc-hint">Total travel expense: <b>{money(Number(f.petrol_amount||0)+Number(f.toll||0)+Number(f.parking||0)+Number(f.other||0))}</b></div>;if(resource==='salary')return <div className="calc-hint">Net salary: <b>{money(Number(f.basic||0)+Number(f.allowance||0)+Number(f.additions||0)-Number(f.deductions||0))}</b></div>;return null}
function Reports(){const [sales,setSales]=useState([]),[expenses,setExpenses]=useState([]),[purchases,setPurchases]=useState([]),[period,setPeriod]=useState('month');useEffect(()=>{Promise.all([listResource('sales'),listResource('expenses'),listResource('purchases')]).then(([s,e,p])=>{setSales(s);setExpenses(e);setPurchases(p)})},[]);const start=new Date();if(period==='month')start.setDate(1);if(period==='year'){start.setMonth(0);start.setDate(1)}const inPeriod=x=>!x.date||new Date(x.date)>=start;const s=sales.filter(inPeriod).reduce((a,x)=>a+Number(x.total_amount||0),0),e=expenses.filter(inPeriod).reduce((a,x)=>a+Number(x.amount||0),0),p=purchases.filter(inPeriod).reduce((a,x)=>a+Number(x.total_amount||0),0);const rows=[['Revenue',s],['Purchases / cost',p],['Operating expenses',e],['Operating profit',s-e]];return <div><div className="toolbar"><div><h2>Reports</h2><p className="muted">Calculated from saved transaction records.</p></div><select className="period-select" value={period} onChange={e=>setPeriod(e.target.value)}><option value="today">Today</option><option value="month">This month</option><option value="year">This year</option></select></div><div className="stats-grid report-grid">{rows.map(([t,v])=><div className="stat-card" key={t}><span>{t}</span><strong>{money(v)}</strong><small>{period==='month'?'Month to date':period==='year'?'Year to date':'Today'}</small></div>)}</div><div className="panel"><div className="panel-head"><div><h3>Report notes</h3><p>Profit is not entered manually. It is derived from saved sales and expenses.</p></div></div><div className="report-list"><div>Sales records <b>{sales.filter(inPeriod).length}</b></div><div>Expense records <b>{expenses.filter(inPeriod).length}</b></div><div>Purchase records <b>{purchases.filter(inPeriod).length}</b></div></div></div></div>}
function SettingsPage({user}){return <div className="settings-grid"><div className="panel"><h3>Business settings</h3><p className="muted">Basic preferences for this local installation.</p><div className="setting-row"><span>Currency</span><b>₹ INR</b></div><div className="setting-row"><span>Application</span><b>Kavish Business Management</b></div><div className="setting-row"><span>API</span><b>http://127.0.0.1:8001/api</b></div></div><div className="panel"><h3>Current user</h3><div className="user-large"><div className="avatar big">{(user?.username||'O')[0].toUpperCase()}</div><div><b>{user?.username||'Owner'}</b><p className="muted">Authenticated internal user</p></div></div><div className="alert info">For production, keep PostgreSQL backups outside the browser and use the backend backup/restore workflow.</div></div><div className="panel"><h3>Mobile app</h3><p className="muted">This frontend is configured as a PWA. After deployment, Chrome can offer “Install app / Add to Home screen”.</p></div></div>}

createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>)
